name: CMake Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v2
      with:
        submodules: 'recursive' # Fetches all submodules recursively

    - name: Create Build Directory
      run: mkdir build

    - name: Configure CMake
      run: cmake .. -DCMAKE_BUILD_TYPE=Release
      working-directory: build

    - name: Build
      run: cmake --build .
      working-directory: build

    - name: Run tests (Run the FlashRadixTree executable)
      run: ./FlashRadixTree
      working-directory: build
