name: CMake Build

on:
  push:
    branches:
      - '*' # Run on any branch push
  pull_request:
    branches:
      - '*' # Run on any pull request
  workflow_dispatch: # Add this line

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v2
      with:
        submodules: 'recursive' # Fetches all submodules recursively

    - name: Print content of a file
      run: cat M1-Cycles/m1cycles.h 
        
    - name: Create Build Directory
      run: mkdir build

    - name: Configure CMake
      run: cmake .. -DCMAKE_BUILD_TYPE=Release
      working-directory: build

    - name: Build
      run: cmake --build .
      working-directory: build

    - name: Run tests (Run the FlashRadixTree executable)
      run: ./FlashRadixTree
      working-directory: build

    - name: Run tests (Run the FlashRadixTreeWithSplay executable)
      run: ./FlashRadixTreeWithSplay
      working-directory: build
